env:
  max_power: 2100
  min_power: 0
  n_days: 3
  time_intervals: 48
  action_list: ['sleep', 'collect', 'send all']
  max_messages: 5
  power_levels: 20

agent:
  alpha: 0.4
  gamma: 0.6
  epsilon: 0.5
  epsilon_decay: 0.999

train:
  num_episodes: 5000