env:
  max_power: 2100
  min_power: 0
  n_days: 90
  time_intervals: 48
  action_list: ['sleep', 'collect', 'send all']
  max_messages: 24
  power_levels: 20

agent:
  alpha: 0.1
  gamma: 0.9
  epsilon: 0.5
  epsilon_decay: 0.9999

train:
  num_episodes: 100000