env:
  max_power: 1300
  min_power: 0
  n_days: 20
  action_list: ['sleep', 'collect', 'send all']
  time_intervals: 48
  max_messages: 5
  power_levels: 400
  cloudy_chance: 0.8
  message_reward: 1.0
  missed_message_penalty: -1.5
  power_reward: 0.0001

agent:
  n_step: 5
  alpha: 0.1
  gamma: 0.9
  epsilon: 1.0
  epsilon_decay: 0.995

train:
  num_episodes: 5000
  reward_power_loss: 0.0
  reward_power_multiplier: 0.0001
  reward_action_0: -0.8136981144168514
  reward_action_1: -0.46005675376689026
  reward_action_2: -1.4517242268429282
  reward_message_count: 0.6404633803633006